backend:
  name: git-gateway
  branch: master
editor:
  preview: false
locale: 'fr'
logo_url: https://unplatsurlaplanche.com/icon.png

publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'recettes'
    label: 'Recettes'
    folder: 'content/recettes'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Informations supplémentaire',
          name: 'infos',
          widget: 'markdown',
          required: false,
        }
      - { label: 'Ingrédients', name: 'ingredients', widget: 'markdown' }
      - label: Étapes
        name: steps
        widget: list
        fields:
          - { label: Contenu, name: content, widget: markdown }
          - label: Images d'étape
            name: 'thumbnailStep'
            widget: 'list'
            required: false
            fields:
              - {
                  label: Image,
                  name: thumbnailStepPreview,
                  widget: image,
                  required: false,
                }
      - label: 'Images fin de recette'
        name: 'thumbnaillist'
        widget: 'list'
        required: false
        fields:
          - { label: Image, name: thumbnail2, widget: image, required: false }

      - {
          label: 'Temps de préparation',
          name: 'preparationtime',
          widget: 'string',
        }
      - {
          label: 'Temps de cuision',
          name: 'bakingtime',
          widget: 'string',
          required: false,
        }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }

  - name: 'blog'
    label: 'Articles'
    folder: 'content/articles'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Résumé', name: 'summary', widget: 'markdown' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }

  - name: 'addresses'
    label: 'Adresses'
    folder: 'content/adresses'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Adresse', name: 'address', widget: 'text' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
